### ISSUE TITLE
Error if no aws profile (i think)

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [ivyleavedtoadflax/remote.py#3]
AWS: reproducibleanalytics    ~/Documents/wellcome  remotepy ls                                                                                                                    <aws:reproducibleanalytics>
Traceback (most recent call last):
  File "/home/matthew/.local/bin/remotepy", line 8, in <module>
    sys.exit(app())
  File "/home/matthew/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/matthew/.local/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/matthew/.local/lib/python3.8/site-packages/remotepy/instance.py", line 134, in list
    widths = get_column_widths([names, ids, public_ips, statuses, instance_types])
  File "/home/matthew/.local/lib/python3.8/site-packages/remotepy/utils.py", line 7, in get_column_widths
    widths.append(max([len(str(i)) for i in column]))
ValueError: max() arg is an empty sequence

**Comment by nsorros** [comment]
I have initialised the package in an empty codespace with no aws configuration and the error I am getting is
```
botocore.exceptions.NoRegionError: You must specify a region.
```

So i think this is not purely related with a lack of aws profile. Let me investigate other potential causes but ultimately we need to find a way to replicate this in order to resolve.

**Comment by nsorros** [comment]
This seems related with an aws profile that has no instances

**Comment by nsorros** [comment]
Since this purely has to do with `get_column_widths` which we have discussed in a separate tool that is not necessary, a simply fix is to simply remove that line and rely on the default auto behaviour https://github.com/explosion/wasabi#tables

**Comment by nsorros** [comment]
I am also not sure this subcommand exists anymore as `ls` does not seem to take arguments but i think #28 should address similar cases
