### ISSUE TITLE
Error if no credentials set

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [ivyleavedtoadflax/remote.py#6]
```
Traceback (most recent call last):
  File "/home/matthew/.local/bin/remotepy", line 8, in <module>
    sys.exit(app())
  File "/home/matthew/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/matthew/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/matthew/.local/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/matthew/.local/lib/python3.8/site-packages/remotepy/instance.py", line 138, in list
    instances = get_instances()
  File "/home/matthew/.local/lib/python3.8/site-packages/remotepy/instance.py", line 53, in get_instances
    return ec2_client.describe_instances()["Reservations"]
  File "/home/matthew/.local/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/matthew/.local/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials

**Comment by nsorros** [comment]
Is this still relevant? Can you provide a reproducible script?

**Comment by nsorros** [comment]
At the moment if no creds are set I get
```
Traceback (most recent call last):
  File "/Users/nsorros/.local/bin/remote", line 5, in <module>
    from remotepy.cli import app
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/remotepy/cli.py", line 2, in <module>
    from remotepy.instance import app as app
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/remotepy/instance.py", line 19, in <module>
    ec2_client = boto3.client("ec2")
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/session.py", line 976, in create_client
    client = client_creator.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/client.py", line 155, in create_client
    client_args = self._get_client_args(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/client.py", line 485, in _get_client_args
    return args_creator.get_client_args(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/args.py", line 92, in get_client_args
    final_args = self.compute_client_args(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/args.py", line 205, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/args.py", line 313, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/args.py", line 418, in _resolve_endpoint
    return endpoint_bridge.resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/client.py", line 590, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/regions.py", line 229, in construct_endpoint
    result = self._endpoint_for_partition(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/regions.py", line 277, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

If I specify the region but no creds
```
Traceback (most recent call last):

  File "/Users/nsorros/.local/bin/remote", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/remotepy/instance.py", line 214, in list
    instances = get_instances()
                ^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/remotepy/instance.py", line 67, in get_instances
    return ec2_client.describe_instances()["Reservations"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/client.py", line 947, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/client.py", line 970, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)

  File "/Users/nsorros/.local/pipx/venvs/remotepy/lib/python3.11/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()

botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by nsorros** [comment]
From the tracebacks there are two sources of those erros

- https://github.com/ivyleavedtoadflax/remote.py/blob/e1b0ce92eca6cc95e2ca7d0ad897ede75c86b7aa/remotepy/instance.py#L67
- https://github.com/ivyleavedtoadflax/remote.py/blob/e1b0ce92eca6cc95e2ca7d0ad897ede75c86b7aa/remotepy/instance.py#L19

The goal would be to add some error handling for those errors in those places.

**Comment by ivyleavedtoadflax** [comment]
Fixed in v0.3.0 - NoCredentialsError is now caught and handled with user-friendly messages
